apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-authors
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-authors
  template:
    metadata:
      labels:
        app: app-authors
    spec:
      containers:
        - name: app-authors
          image:  lrsuniga/app-authors:latest
          ports:
            - containerPort: 9090
---

apiVersion: v1
kind: Service
metadata:
  name: app-authors-service
spec:
  type: ClusterIP
  selector:
    app: app-authors
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090