apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-books
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-books
  template:
    metadata:
      labels:
        app: app-books
    spec:
      containers:
        - name: app-books
          image:  lrsuniga/app-books:latest
          env:
            - name: APP_AUTHORS_URL
              value: http://app-authors-service:9090
          ports:
            - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: app-books-service
spec:
  type: ClusterIP
  selector:
    app: app-books
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080